spring:
  jpa:
    generate-ddl: false
    show-sql: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yolo
    username: yolo
    password: 'qksksk33##'
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp