spring:
  jpa:
    generate-ddl: false
    show-sql: false
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/test
    username: root
    password: 'todnxnlrla33##'